import { test } from "node:test"
import assert from "node:assert/strict"
import { execFile, spawnSync } from "node:child_process"
import { readFile, writeFile, mkdtemp, readdir, access, readlink, lstat, mkdir, symlink } from "node:fs/promises"
import { tmpdir } from "node:os"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { promisify } from "node:util"

const run = promisify(execFile)
const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const apply = join(root, "bin", "omarunner-apply")
const setup = join(root, "bin", "omarunner-setup")
const cli = join(root, "bin", "omarunner")

// Every run points at a disposable directory; the real ~/.config is never read
// or written, and Hyprland is never reloaded (no HYPRLAND_INSTANCE_SIGNATURE).
async function sandbox(config) {
  const dir = await mkdtemp(join(tmpdir(), "omarunner-keys-"))
  const env = {
    PATH: process.env.PATH,
    HOME: dir,
    OMARUNNER_CONFIG: join(dir, "omarunner.json"),
    OMARUNNER_HYPRLAND_LUA: join(dir, "hyprland.lua"),
    OMARUNNER_LUA_OUT: join(dir, "omarunner.lua"),
    OMARUNNER_BIN_DIR: join(dir, "bin")
  }
  if (config !== undefined) await writeFile(env.OMARUNNER_CONFIG, JSON.stringify(config))
  await writeFile(env.OMARUNNER_HYPRLAND_LUA, "-- user config\nhl.config({})\n")
  return { dir, env }
}
const go = (script, args, env) => run(script, args, { env })
const read = p => readFile(p, "utf8")

test("apply writes the default binds and loads them once from hyprland.lua", async () => {
  const { env } = await sandbox()
  await go(apply, [], env)
  const lua = await read(env.OMARUNNER_LUA_OUT)
  assert.match(lua, /GENERATED by omarunner-apply/)
  assert.ok(lua.includes('bind("SUPER + SPACE", "omarunner",'))
  assert.ok(lua.includes('bind("SUPER + ALT + SPACE", "omarunner apps",'))
  assert.ok(lua.includes("/.config/omarchy/plugins/videinfra.omarunner/bin/omarunner"))
  const hypr = await read(env.OMARUNNER_HYPRLAND_LUA)
  assert.equal(hypr.split("videinfra.omarunner/omarunner.lua").length - 1, 1)
  assert.ok(hypr.startsWith("-- user config"))
})

test("apply is idempotent: no second loader, no extra backup", async () => {
  const { dir, env } = await sandbox()
  await go(apply, [], env)
  await go(apply, [], env)
  const hypr = await read(env.OMARUNNER_HYPRLAND_LUA)
  assert.equal(hypr.split("videinfra.omarunner/omarunner.lua").length - 1, 1)
  const backups = (await readdir(dir)).filter(f => f.startsWith("hyprland.lua.bak."))
  assert.equal(backups.length, 1)
})

test("the generated Lua parses and binds what the config says", async () => {
  const { env } = await sandbox({ keys: { launcher: "SUPER + R", apps: "none" } })
  await go(apply, [], env)
  const lua = await read(env.OMARUNNER_LUA_OUT)
  assert.ok(lua.includes('bind("SUPER + R", "omarunner",'))
  assert.equal(lua.includes("omarunner apps"), false)
  assert.equal(spawnSync("luac", ["-p", env.OMARUNNER_LUA_OUT]).status, 0)
  // Run it against a stub `hl`: it must unbind, then bind, each key once.
  const stub = `local calls = {}
    hl = { unbind = function(k) calls[#calls+1] = "unbind " .. k end,
           bind = function(k, d, o) calls[#calls+1] = "bind " .. k .. " " .. o.description end,
           dsp = { exec_cmd = function(c) return c end } }
    dofile("${env.OMARUNNER_LUA_OUT}")
    print(table.concat(calls, ";"))`
  const out = spawnSync("lua", ["-e", stub], { env: { ...process.env, HOME: env.HOME } })
  assert.equal(out.stdout.toString().trim(), "unbind SUPER + R;bind SUPER + R omarunner")
})

test("apply rejects an unusable key and writes nothing", async () => {
  const { env } = await sandbox({ keys: { launcher: 'SUPER + "X"' } })
  await assert.rejects(go(apply, [], env), e => /not a usable key/.test(e.stderr))
  await assert.rejects(access(env.OMARUNNER_LUA_OUT))
  const same = await sandbox({ keys: { launcher: "SUPER + R", apps: "SUPER + R" } })
  await assert.rejects(go(apply, [], same.env), e => /same key/.test(e.stderr))
})

test("apply --remove takes the loader and the generated file away again", async () => {
  const { env } = await sandbox()
  await go(apply, [], env)
  await go(apply, ["--remove"], env)
  const hypr = await read(env.OMARUNNER_HYPRLAND_LUA)
  assert.equal(hypr.includes("videinfra.omarunner"), false)
  assert.ok(hypr.includes("hl.config({})"))
  await assert.rejects(access(env.OMARUNNER_LUA_OUT))
})

test("setup --yes writes the keys into the config and applies them", async () => {
  const { env } = await sandbox({ sources: { files: false } })
  await go(setup, ["--yes", "--launcher", "SUPER + R", "--apps", "none"], env)
  const config = JSON.parse(await read(env.OMARUNNER_CONFIG))
  assert.deepEqual(config.keys, { launcher: "SUPER + R", apps: "none" })
  assert.deepEqual(config.sources, { files: false })
  assert.ok((await read(env.OMARUNNER_LUA_OUT)).includes('bind("SUPER + R"'))
})

test("setup refuses to overwrite a config that is not valid JSON", async () => {
  const { env } = await sandbox()
  await writeFile(env.OMARUNNER_CONFIG, "{ not json")
  await assert.rejects(go(setup, ["--yes", "--launcher", "SUPER + R"], env), e => /not valid JSON/.test(e.stderr))
  assert.equal(await read(env.OMARUNNER_CONFIG), "{ not json")
})

test("the CLI offers setup and apply, and lists them in its help", async () => {
  const { stdout } = await run(cli, ["--help"], { env: process.env })
  assert.match(stdout, /setup/)
  assert.match(stdout, /apply/)
  const script = await read(cli)
  assert.ok(script.includes("omarunner-setup") && script.includes("omarunner-apply"))
})

// -- PATH link and optional packages.

test("setup --yes puts omarunner on the PATH with a link into the plugin's bin", async () => {
  const { env } = await sandbox()
  await go(setup, ["--yes"], env)
  assert.equal(await readlink(join(env.OMARUNNER_BIN_DIR, "omarunner")), cli)
  await go(setup, ["--yes"], env) // re-running is fine
  assert.equal(await readlink(join(env.OMARUNNER_BIN_DIR, "omarunner")), cli)
})

test("setup --no-path leaves the PATH alone, and never replaces someone else's omarunner", async () => {
  const a = await sandbox()
  await go(setup, ["--yes", "--no-path"], a.env)
  await assert.rejects(lstat(join(a.env.OMARUNNER_BIN_DIR, "omarunner")))
  const b = await sandbox()
  await mkdir(b.env.OMARUNNER_BIN_DIR)
  await writeFile(join(b.env.OMARUNNER_BIN_DIR, "omarunner"), "#!/bin/sh\n")
  const { stdout } = await go(setup, ["--yes"], b.env)
  assert.equal(await read(join(b.env.OMARUNNER_BIN_DIR, "omarunner")), "#!/bin/sh\n")
  assert.match(stdout, /already exists/)
})

test("apply --remove removes the PATH link it made, and only that one", async () => {
  const { env } = await sandbox()
  await go(setup, ["--yes"], env)
  await go(apply, ["--remove"], env)
  await assert.rejects(lstat(join(env.OMARUNNER_BIN_DIR, "omarunner")))
  const other = await sandbox()
  await mkdir(other.env.OMARUNNER_BIN_DIR)
  await symlink("/usr/bin/true", join(other.env.OMARUNNER_BIN_DIR, "omarunner"))
  await go(apply, ["--remove"], other.env)
  assert.equal(await readlink(join(other.env.OMARUNNER_BIN_DIR, "omarunner")), "/usr/bin/true")
})

test("setup names missing optional packages", async () => {
  const { dir, env } = await sandbox()
  const tools = join(dir, "tools")
  await mkdir(tools)
  for (const t of ["bash", "env", "jq", "dirname", "readlink", "mkdir", "ln", "cp", "mv", "mktemp", "date", "grep", "rm", "cat"]) {
    const r = spawnSync("which", [t])
    if (r.status === 0) await symlink(r.stdout.toString().trim(), join(tools, t))
  }
  const { stderr } = await go(setup, ["--yes"], { ...env, PATH: tools })
  assert.match(stderr, /libqalculate \(qalc\)/)
  assert.match(stderr, /fzf: fuzzy ranking/)
  assert.match(stderr, /fd: file and folder search/)
})
